// <auto-generated />
using Apple.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apple.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Apple.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Wearable",
                            Description = "Smartwatch dari Apple",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple Watch",
                            Price = 299.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Smartphone",
                            Description = "Smartphone terbaru dari Apple",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "iPhone 15",
                            Price = 999.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Laptop",
                            Description = "Laptop performa tinggi",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "MacBook Pro",
                            Price = 1999.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Tablet",
                            Description = "Tablet ringan dan cepat",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "iPad Air",
                            Price = 599.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Aksesoris",
                            Description = "Earbuds nirkabel dengan noise cancelling",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "AirPods Pro",
                            Price = 249.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Desktop",
                            Description = "All-in-one desktop komputer",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "iMac 24\"",
                            Price = 1299.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Aksesoris",
                            Description = "Stylus untuk iPad",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple Pencil",
                            Price = 129.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Aksesoris",
                            Description = "Mouse wireless dari Apple",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Magic Mouse",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Smart Home",
                            Description = "Speaker pintar dari Apple",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "HomePod Mini",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Entertainment",
                            Description = "Streaming device 4K",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple TV 4K",
                            Price = 179.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Desktop",
                            Description = "Komputer kecil namun bertenaga",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Mac Mini",
                            Price = 699.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Aksesoris",
                            Description = "Pelacak barang pintar",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "AirTag",
                            Price = 29.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Aksesoris",
                            Description = "Keyboard wireless slim",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple Keyboard",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "Smartphone",
                            Description = "iPhone murah dengan performa tinggi",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "iPhone SE",
                            Price = 429.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "Tablet",
                            Description = "Tablet kecil dengan kekuatan besar",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "iPad Mini",
                            Price = 499.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "Display",
                            Description = "Layar monitor 5K",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple Studio Display",
                            Price = 1599.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "Desktop",
                            Description = "Desktop powerful untuk kreator",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Mac Studio",
                            Price = 1999.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "Smartphone",
                            Description = "iPhone flagship",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "iPhone 14 Pro Max",
                            Price = 1199.0
                        },
                        new
                        {
                            Id = 19,
                            CategoryName = "Aksesoris",
                            Description = "Trackpad besar dan responsif",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Magic Trackpad",
                            Price = 129.0
                        },
                        new
                        {
                            Id = 20,
                            CategoryName = "Wearable",
                            Description = "Smartwatch ekstrem untuk olahraga outdoor",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple Watch Ultra",
                            Price = 799.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
