version: '3.8'

services:
  # --- Database Services ---
  authdb:
    image: mcr.microsoft.com/mssql/server 

  menudb:
    image: mcr.microsoft.com/mssql/server  

  distributedcache:
    image: redis

  # --- API Services (Hanya definisi build image) ---
  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .  
      dockerfile: Services/Auth/Auth.API/Dockerfile 

  menu.api:
    image: ${DOCKER_REGISTRY-}menuapi
    build:
      context: .
      dockerfile: Services/Menu/Menu.API/Dockerfile  
       
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: Gateways/YarpApiGateway/Dockerfile

volumes:
  mssql_auth:
  mssql_menu: 

